## Check for required R package

if(!library(ineq, logical.return=T))
{
  stop("\nPlease install the required package ineq.\n")
} else {
  cat("\nAll required packages have been installed.\n")
}

#################### OBTAIN & CHECK USER-DEFINED VARIABLES ####################

## Obtain the path for the directory that contains the FASTQ files from the user
data.dir <- readline(prompt = "\nEnter the path for (or drag and drop) the folder that contains the FASTQ files to be analyzed. Note that all FASTQ files should have the extension *.fastq.\n")

## Check for the presence of the directory containing the FASTQ files
if(!file.exists(data.dir)) {stop("ERROR: Directory not found!")}

## Check that the directory contains FASTQ files
if(sum(grepl(".fastq$", list.files(data.dir)))<1) {stop("ERROR: No FASTQ files found in the directory!")}

## Obtain the path for the file containing the sgRNA sequences from the user
lib.name <- readline(prompt = "\n\nEnter the path for (or drag and drop) the file that contains the sgRNA sequences. The sgRNA library file should have no headers and should contain three tab-delimited columns: the sgRNA number, the sgRNA name, and the sgRNA sequence (5'-3').\n")

## Check for the presence of the file containing the sgRNA sequences
if(!file.exists(lib.name)) {stop("ERROR: sgRNA file not found!")}

## Obtain the path for the results directory
out.dir <- readline(prompt = "\n\nEnter the path for (or drag and drop) the folder where results should be saved. Alternatively, provide a name for such a folder to be generated in the local directory.\n")

## Check for the presence of the results directory, or create it.
if(!file.exists(out.dir)) 
{
  dir.create(out.dir)
  out.dir <- paste0(getwd(),"/",out.dir)
}

## Provide the user with the available FASTQ files
cat("\n")
print(data.frame(file.name=list.files(data.dir)[grepl(".fastq$",list.files(data.dir))]))

## Ask the user to identify the library
L <- readline(prompt = "\nEnter the number next to the file that represents the library or reference population: ")

## use the prompt to record the library path name
L <- list.files(data.dir)[as.numeric(L)]

## Ask the user to identify the experimental sample
P3 <- readline(prompt = "\nEnter the number next to the file that represents the experimental or selected population: ")

## use the prompt to record the experimental population path name
P3 <- list.files(data.dir)[as.numeric(P3)]

cat("\nThe following file has been selected as the reference:", L, "\nThe following file has been selected as the experimental sample:", P3, "\n")

################################################################

## Execute Countess on the relevant files, generating a file for each sample that lists the number of times a given sgRNA was found in that sample.
cat("\nThe FASTQ files are being analyzed to count the number of sgRNAs in each sample. Depending on the size of the files this may take several minutes.\n")
system2("perl", args = c("Countess -l ",lib.name, " -d ", data.dir, " -o ", out.dir))

## Aggregate the counted reference (L) and experimental (P3) counted samples into a data frame called "DF.sg" that lists the number of times each sgRNA was found in each sample. The counted files are generated by the Perl program 'Countess' and each contains two tab-delimited columns: one with the guide IDs, the other with the number of times each guide was found.

L <- sub(".fastq$","", L)
P3 <- sub(".fastq$","", P3)

DF.raw <- data.frame()
counted_path <- paste0(data.dir, "_Counted/",L)
DF.raw <-read.table(counted_path, row.names=1)
colnames(DF.raw) <- c(L)
counted_path <- paste0(data.dir, "_Counted/",P3)
temp_dataset <- read.table(counted_path, row.names=1)
colnames(temp_dataset) <- c(P3)
DF.raw<-merge(DF.raw, temp_dataset, by="row.names", all=T)
rownames(DF.raw)<-DF.raw[,1]
DF.raw[,1]<-NULL
rm(temp_dataset)

## Match normalize
DF.sg <- DF.raw
for (i in 1:ncol(DF.sg))
{
  x.sum <- sum(DF.sg[,i])
  DF.sg[,i] <- c(DF.sg[,i]/x.sum)
}

## Calculate Gini indices and print out Lorenz curve plot
gini.L <- signif(Gini(DF.sg[,L]), digits=4)
gini.P3 <- signif(Gini(DF.sg[,P3]), digits=4)
cat("\nThe following Gini indices have been calculated for the samples:\n\t", L, "\t", gini.L, "\n\t", P3, "\t", gini.P3, "\n")

pdf(paste0(out.dir,"/LorenzCurves.pdf"))
par(pty="s")
plot(Lc(DF.sg[,L]), lwd=3, col="sky blue")
lines(Lc(DF.sg[,P3]), lwd=3, col="orange")
legend("topleft", title="", c("reference", "experimental sample"),  bty="n", lwd=3, col=c("sky blue", "orange"))
dev.off()

cat("\nA graph called 'LorenzCurves.pdf' has been saved in the results folder.\n")

## Replace zeros
for (i in 1:ncol(DF.sg))
{
  x <- DF.sg[,i]
  x[x == 0] <- NA
  x[is.na(x)] <- .9*min(x, na.rm=T)
  DF.sg[,i] <- x
  rm(x)
}

## Log2 transform
DF.sg <- log2(DF.sg)

## Define the quantile to exclude
Q <- 0.05 #quantile to be used in pruning

## Remove the sgRNAs in the lowest quantile of the library
DF.sg <- DF.sg[DF.sg[,L] > quantile(DF.sg[,L], Q, na.rm = T),]

## Calculate fold change
DF.sg$FC<-c(DF.sg[,P3]-DF.sg[,L])

## The resulting DF.sg data frame lists the log2(relative abundance) of each sgRNA in each sample and the fold change between the reference sample and the experimental sample (FC column).

## Extract the gene IDs from the sgRNA IDs
cat("\nThe phenotype score for each gene will be calculated from the fold-change in its sgRNAs. This may take several minutes.\n")

DF.sg$ID <- sub(".*(TGGT1_[0-9]+[A-Z]?).*","\\1",rownames(DF.sg))

## Create a new data frame called "DF.genes" with the gene IDs
DF.genes <- data.frame(ID=unique(DF.sg$ID))

## Define the function to calculate standard error of the mean (SEM)
sem <- function(x) sd(x, na.rm=T)/sqrt(sum(!is.na(x)))

## Calculate the phenotype score and its SEM.
## n equals the number of sgRNAs used in the calculation.
for (i in 1:length(DF.genes$ID))
{
  gene <- as.character(DF.genes$ID[i])
  scores <- subset(DF.sg, DF.sg$ID == gene)[,"FC"]
  scores <- scores[!is.na(scores)]
  if (length(scores) > 5)
  {
    scores <- scores[order(-scores)]
    DF.genes$phenotype[i] <- mean(scores[1:5])
    DF.genes$sem[i] <- sem(scores[1:5])
    DF.genes$n[i] <- 5
  }
  else if (length(scores) >= 2)
  {
    DF.genes$phenotype[i] <- mean(scores)
    DF.genes$sem[i] <- sem(scores)
    DF.genes$n[i] <- length(scores)
  }
  else
  {
    DF.genes$phenotype[i] <- NA
    DF.genes$sem[i] <- NA
    DF.genes$n[i] <- length(scores)
  }
}

## Rank-order the genes and plot by phenotype
DF.genes <- DF.genes[order(DF.genes$phenotype),]
DF.genes$pos <- c(1:length(DF.genes$ID))

## Define parameters for graphing and plot
SE.up = DF.genes$phenotype + DF.genes$sem
SE.dn = DF.genes$phenotype - DF.genes$sem

pdf(paste0(out.dir,"/PhenotypeCurves1.pdf"))
plot(DF.genes$phenotype~DF.genes$pos,pch=20, cex=0.1, las=1, ylab="phenotype", xlab="rank-ordered genes")
abline(0,0)
arrows(DF.genes$pos,SE.dn,DF.genes$pos,SE.up,code=3,length=0,angle=90,col='gray85')
points(DF.genes$phenotype~DF.genes$pos, pch=20, cex=.5)

dispensable.IDs <- c("TGGT1_292055","TGGT1_295760","TGGT1_217600","TGGT1_240390","TGGT1_232130","TGGT1_235380","TGGT1_225490","TGGT1_205380","TGGT1_297880","TGGT1_255190","TGGT1_283510","TGGT1_246940","TGGT1_228400","TGGT1_243400","TGGT1_309870","TGGT1_253770","TGGT1_306620","TGGT1_305860","TGGT1_205480","TGGT1_310160","TGGT1_286590","TGGT1_201840","TGGT1_205250","TGGT1_233030","TGGT1_260820","TGGT1_262730","TGGT1_204130","TGGT1_277080","TGGT1_263180","TGGT1_250880","TGGT1_227620","TGGT1_312480","TGGT1_309590","TGGT1_233460","TGGT1_315760","TGGT1_294690","TGGT1_254555","TGGT1_282055","TGGT1_254470","TGGT1_319560")

essential.IDs <- c("TGGT1_289910","TGGT1_203010","TGGT1_254120","TGGT1_247510","TGGT1_312570","TGGT1_274000","TGGT1_313380","TGGT1_215700","TGGT1_256960","TGGT1_256920","TGGT1_311470","TGGT1_228750","TGGT1_261440","TGGT1_240910","TGGT1_253040","TGGT1_216080","TGGT1_223940","TGGT1_301440","TGGT1_255370","TGGT1_245490","TGGT1_293690","TGGT1_235470","TGGT1_243250","TGGT1_311310","TGGT1_249970","TGGT1_227970","TGGT1_220400","TGGT1_261070","TGGT1_287270","TGGT1_278870","TGGT1_209030","TGGT1_462965","TGGT1_310440","TGGT1_236110","TGGT1_290160","TGGT1_311360","TGGT1_244380")

dispensable.phenotypes <- subset(DF.genes, DF.genes$ID %in% dispensable.IDs)
essential.phenotypes <- subset(DF.genes, DF.genes$ID %in% essential.IDs)
Ref.mean <- mean(dispensable.phenotypes$phenotype)

points(dispensable.phenotypes$pos, dispensable.phenotypes$phenotype, col="orange", pch=19)

points(essential.phenotypes$pos, essential.phenotypes$phenotype, col="sky blue", pch=19)

abline(h=Ref.mean, lty=2, lwd=2, col="orange")

legend("bottomright", title="", c("dispensable mean", "known dispensable", "known essential"), horiz=F, cex=1, bty="n", lty=2, lwd=2, col=c("orange", "transparent", "transparent"), text.col="transparent")
legend("bottomright", title="", c("mean phenotype", "known dispensable", "known essential"), horiz=F, cex=1, bty="n", pch=19, col=c("transparent", "orange", "sky blue"))

dev.off()

cat("\nA graph called 'PhenotypeCurves1.pdf' has been saved in the results folder.\n")

cat("\nThe probability of being fitness conferring will be calculated for each gene based on the distribution of its sgRNA values and those of control genes. This may take a few minutes.\n")

## Extract the sgRNA values for the control genes
control <- subset(DF.sg, DF.sg$ID %in% dispensable.IDs)

## Calculate the p value for each gene
for (i in 1:length(DF.genes$ID))
{
  scores <- DF.sg$FC[DF.sg$ID==as.character(DF.genes$ID[i])]
  scores <- scores[!is.na(scores)]
  if (length(scores) > 2)
  {
    DF.genes$p.value[i] <- wilcox.test(scores,control$FC, alternative = "less")$p.value
  } else {
    DF.genes$p.value[i] <- NA
  }
}

## Correct the p values for multiple hypothesis testing
DF.genes$FDR = p.adjust(DF.genes$p.value, method="fdr")

## Define fitness conferring genes as those with FDR less than or equal to 0.05
for (i in 1:length(DF.genes$ID))
{
  if (!is.na(DF.genes$FDR[i]) & DF.genes$FDR[i] <= 0.05)
  {
    DF.genes$fitness.conferring[i] <- "TRUE"  
  } else {
    DF.genes$fitness.conferring[i] <- "FALSE"  
  }
}

## Extract the fitness conferring genes
pdf(paste0(out.dir,"/PhenotypeCurves2.pdf"))
fitness.conferring <- DF.genes[DF.genes$fitness.conferring=="TRUE",]

## Plot highlighting the fitness-conferring genes
plot(DF.genes$phenotype~DF.genes$pos,pch=20, cex=0.1, las=1, ylab="phenotype", xlab="rank-ordered genes")
abline(0,0)
arrows(DF.genes$pos,SE.dn,DF.genes$pos,SE.up,code=3,length=0,angle=90,col='gray85')
points(DF.genes$phenotype~DF.genes$pos, pch=20, cex=.5)

points(fitness.conferring$pos, fitness.conferring$phenotype, col="red", pch=19)

abline(h=Ref.mean, lty=2, lwd=2, col="orange")

legend("bottomright", title="", c("mean phenotype", "fitness-conferring"), horiz=F, cex=1, bty="n", lty=2, lwd=2, col=c("orange", "transparent"), text.col="transparent")
legend("bottomright", title="", c("mean phenotype", "fitness-conferring"), horiz=F, cex=1, bty="n", pch=19, col=c("transparent", "red"))

dev.off()

cat("\nA graph called 'PhenotypeCurves2.pdf' has been saved in the results folder.\n")

## Save data frame
write.csv(DF.raw, file=paste0(out.dir, "/", "sgRNA_Counts.csv"))
cat("\nThe raw sgRNA counts were saved to the results folder under the name 'sgRNA_Counts.csv'.\n")
write.csv(DF.sg, file=paste0(out.dir, "/", "sgRNA_FoldChange.csv"))
cat("\nThe log2 relative abundance and fold change for each sgRNA were saved to the results folder under the name 'sgRNA_FoldChange.csv'.\n")
write.csv(DF.genes, file=paste0(out.dir, "/", "GenePhenotypes.csv"), row.names=F)
cat("\nThe phenotype scores and associated statistics for each gene were saved to the results folder under the name 'GenePhenotypes.csv'.\n")
cat("\nCRISPR_Analysis is now complete. You may quit R and close the terminal window.\n")
